        <div id="info_toolbar">
            

                <ul id="info_tool_menu" class="menu_clear">
                    <a class="link_clear" href="
                        <?php echo $this->url(array(
                                    'controller' =>'index',
                                    'action' => 'show-search-hotel'));?>">
                        <li>
                            <div id="info_tool_menu_1" class="info_tool_menu">
                                <div class="info_tool_menu_left">
                                  wyszukiwarka<br>hoteli
                                </div>
                                <div class="info_tool_menu_right">
                                  <img src='<?php echo $this->serverUrl();?>/images/menu/loop_logo.png' />
                                </div>
                            </div>
                        </li>
                    </a>

                    <a class="link_clear" href="
                        <?php echo $this->url(array(
                                    'controller' =>'index',
                                    'action' => 'reservation-info'));?>">
                        <li>
                            <div id="info_tool_menu_2" class="info_tool_menu">
                                <div class="info_tool_menu_left special_1">
                                rezerwacje
                                </div>
                                <div class="info_tool_menu_right">
                                <img src='<?php echo $this->serverUrl();?>/images/menu/reservation_logo.png' />
                                </div>
                            </div>
                        </li>
                    </a>

                    <a class="link_clear" href="
                    <?php echo $this->url(array(
                                    'controller' =>'index',
                                    'action' => 'system-info'));?>">
                        <li>
                            <div id="info_tool_menu_3" class="info_tool_menu">
                                <div class="info_tool_menu_left special_2">
                                system<br>zarządzania<br>hotelem
                                </div>
                                <div class="info_tool_menu_right">
                                <img src='<?php echo $this->serverUrl();?>/images/menu/cms_logo.png' />
                                </div>
                            </div>
                        </li>
                    </a>

                    <a class="link_clear" href="<?php echo $this->url(array(
                                                                            'controller' =>'index',
                                                                            'action' => 'add-hotel-start'));?>">
                        <li>
                            <div id="info_tool_menu_4" class="info_tool_menu">
                                <div class="info_tool_menu_left">
                                dodaj hotel<br>do bazy
                                </div>
                                <div class="info_tool_menu_right">
                                <img src='<?php echo $this->serverUrl();?>/images/menu/hotel_logo.png' />
                                </div>
                            </div>
                        </li>
                    </a>

                </ul>

            </div>
         


                 
            <!--div id="info_toolbar_right">
                <a class="link_clear" href="#">
                    <div id="go_to_add_hotel">
                        <span class="info_toolbar_text_1">Dodaj swój hotel do bazy</span><br />
                        <span class="info_toolbar_text_2">całkowicie za darmo</span>
                    </div>
                </a>

            </div>


        </div-->

             <!--div id="search_container">
            <div id="search_row">
                <div id="search_label">
                        <span>WYSZUKAJ HOTEL</span>
                </div>

                <div id="search_zoom">
                    <a href="#"><img src="../images/main_page/zoom.png" /></a>
                </div>

                <div id="search_right">
                    <div id="search_right_top">
                        <div id="search_right_top_left">
                            <div class="search_label_2">
                                miasto:
                            </div>
                            <div class="search_input">
                            </div>

                        </div>

                        <div id="search_right_top_middle">
                            <div class="search_label_2">
                                standard hotelu:
                            </div>
                            <div class="search_input">
                            </div>
                        </div>

                        <div id="search_right_top_right">
                            <a class="link_clear" href="#">
                                <div id="search_button_content">
                                    SZUKAJ
                                    <img src="../images/main_page/grey_double_dart.png" />
                                </div>
                            </a>

                        </div>

                    </div>

                    <div id="search_right_bottom">
                        <a class="link_clear" href="#">
                            <span>zaawansowana wyszukiwarka hoteli</span>
                            <img src="../images/main_page/yellow_double_dart.png" />
                        </a>
                    </div>

                </div>



            </div>


        </div>
             -->


             <!--
             KOPIA ZAPASOWA

                <div id="info_toolbar">
            <div id="info_toolbar_left">

                <ul id="info_tool_menu" class="menu_clear">
                    <a class="link_clear" href="#">
                        <li><div style="width: 256px;">

                                <div class="type_of_hotel">
                                    <img src="../images/main_page/type_of_hotel.png" />
                                </div>

                                <div class="info_tool_label">
                                    <span style="color:#0bbc3e; text-align: center;">
                                        <center>wyszukiwarka hoteli, pól<br />
                                        namiotywch i campingowych</center>
                                    </span>
                                </div>

                        </div></li>
                    </a>

                    <a class="link_clear" href="#">
                        <li ><div style="width: 94px; margin-left: 15px; margin-right: 15px;">
                                <div class="reservation_room">
                                    <img src="../images/main_page/reservation_room.png" />
                                </div>
                                 <div class="info_tool_label">
                                    <span style="color:#f2d619;">
                                        <center>rezerwacje</center>
                                    </span>
                                 </div>

                        </div></li>
                    </a

                    <a class="link_clear" href="#">
                        <li><div style="width: 217px;">
                                <div class="system_reservation">
                                      <img src="../images/main_page/system_reservation.png" />
                                </div>
                                <div class="info_tool_label">
                                    <span style="color:#cb3912; text-align: center;">
                                        <center>system zarządzania <br />
                                        rezerwacajmi i pokojami</center>
                                    </span>
                                </div>

                        </div></li>
                    </a>

                    <a class="link_clear" href="#">
                        <li>
                            <div>

                            </div>

                        </li>


                    </a>

                </ul>

            </div>

            <div id="info_toolbar_right">
                <a class="link_clear" href="#">
                    <div id="go_to_add_hotel">
                        <span class="info_toolbar_text_1">Dodaj swój hotel do bazy</span><br />
                        <span class="info_toolbar_text_2">całkowicie za darmo</span>
                    </div>
                </a>

            </div>


        </div>




             -->