<div id="sidebar_menu" class="sidebar_menu_normal">
<ul class="menu_sidebar" >
    
    <a id='panel-client-profil' class="link_clear" href="<?php echo $this->url(array('controller'=>'panel-client', 'action'=>'profil'));?>">
        <li>mój profil</li>
    </a>
    
    <a id='panel-client-address' class="link_clear" href="<?php echo $this->url(array('controller'=>'panel-client', 'action'=>'address'));?>">
        <li>Dane Adresowe</li>
    </a>
    
</ul>
</div>

