<ul id="navigate_menu_1">
    <span style="font-size: 16px;"><center>Przejdź do:</center></span>
    <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>" class="link_clear">
        <li class="navi_green_1">strona startowa</li>
    </a>

     <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'show-search-hotel')); ?>">
        <li class="navi_green_1">wyszukiwarka</li>
    </a>


</ul>