<!--ul id="navigate_menu_1">
    <span style="font-size: 16px;"><center>Przejdź do:</center></span>
    <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>" class="link_clear">
        <li class="navi_green_1">strona startowa / wyszukiwarka</li>
    </a>

    <a href="<?php echo $this->url(array('controller' => 'panel-client', 'action' => 'start')); ?>" class="link_clear">
        <li class="navi_blue_1">Konto użytkownika</li>
    </a>
    
    <a href="<?php echo $this->url(array('controller' => 'manage-hotel', 'action' => 'start')); ?>" class="link_clear">
        <li class="navi_red_1">system zarządzania hotelem</li>
    </a>

</ul--> 