<?php echo $this->formRoom;?>

<form id='room_details'>
	<input type="hidden" name="id_room" value="0">

	<div class="edit_2_container br_color_red ">
		<div class="row_1_sec">
			<div class="row_2_sec_lf">
					<div class='..._error error_form'>
					</div>
			</div>
			<div class="row_2_sec">
					<div class='..._error error_form'>
					</div>			
			</div>
		</div>

		<div class="row_1_sec">
			<div class="row_2_sec_lf">
					<div class='..._error error_form'>
					</div>			
			</div>
			<div class="row_2_sec">
					<div class='..._error error_form'>
					</div>			
			</div>
		</div>

		<div class="row_1_sec">
			<div class="row_2_sec_lf">
					<div class='..._error error_form'>
					</div>			
			</div>
			<div class="row_2_sec">
					<div class='..._error error_form'>
					</div>			
			</div>
		</div>

		<div class="row_1_sec">
					<div class='..._error error_form'>
					</div>					
		</div>
	</div>

</form>