<div id='list_hotel'>
	<?php if(count($this->listHotel)){?>
	    <?php foreach($this->listHotel as $singleHotelKey => $singleHotel){
	    ?>
	        <div class="single_hotel_home"> 
	        <?php echo $this-> partial('partialViews/singleHotel.phtml',
	            array('dataHotel' => $singleHotel)
	            );
	        ?>
	        </div>
	        
	    <?php }
	} else {  ?>
		<center>
			<span style='color:red; font-weight:bold;'>
				Nie znaleziono żadnej oferty!
			</span>
		</center>
	<?php }?>


</div>

<script src="<?php echo $this->baseUrl('js/list_offers.js') ?>"></script>