<div class="add_hotel_start">
	<center>
		Utwórz konto w systemie  <b>systemu zarządzania hotelem</b> który:
		</br> - ułatwi Ci <span style='color:#eacf16'><b>zarządzanie rezerwacjami pokoi</b></span>, 
		<br> - zarządzaniem i tworzeniem <span style='color:#ca401a'><b>nowych ofert</b> </span> dla Twoich klientów oraz 
		<br> - udostępni oferty Twojego hotelu w naszym serwisie i <span style='color:#09b32e'><b> powiększy Twoje dochody. </b></span> 
	</center>
</div>

<div class="add_hotel_start">
<center>
	<b>Aby dodać hotel należy:</b> <br>

		- <span style='color:#0398ca'><b>zalogować</b></span> się do panelu zarządzania <br>
			lub jeśli nie posiadasz jeszcze konta zarejestrować się<br>
		- <b>uzupełnić wymagane informajce o hotelu</b> <br>
	</li>
	</ul>

</center>
</div>