<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
  <head>
    <title>Baza hotelowa</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('bootstrap/css/bootstrap.min.css'); ?>"/>

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/clear_style.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/website.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/form.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/decorator.css'); ?>"/>

    <script src="http://code.jquery.com/jquery.js"></script>

    <script src="<?php echo $this->baseUrl('js/test.js') ?>"></script>


    <?php // echo $this->jQuery(); ?>

  </head>

<body id="page" style="padding-left: 100px; padding-top: 100px;">
    <?php echo $this->layout()->content; ?>

</body>
</html>

<!--
#347C32
#3F8332
#4A8A31
#549130
#5F982E
#699F2C
#74A72A
#7FAF27
#8AB823
#95C11E


czerowny


#BE1621
#C32C23
#C93D25
#CF4E28
#D55F2A
#DC702C
#E3802E
#EA9130
#F1A131
#F9B233

-->